% This script plots the figures validating the Repast WoundABM against the 
% original MATLAB ABM (published J Physiol 2012) and experimental data 
% generated by Greg Fomovsky and Laura Caggiano.

% Author: Arlynn C Baker
% Created: 2020/09/17

clear; clc; close all;
addpath('C:\Users\acb4ft\Desktop\WoundABM\woundABMSim\output\Standard');
% original_C=readModelData('UniaxC_10.0_20200917_161545');
% original_L=readModelData('UniaxL_10.0_20200917_163634');
% original_B=readModelData('Biax_10.0_20200917_160011');
original_C=readModelData('UniaxC_2.5_20200922_130643');
original_L=readModelData('UniaxL_2.5_20200922_130706');
original_B=readModelData('Biax_2.5_20200922_130618');
original_models={original_C,original_L,original_B};

% FinalCombinationWithMechanicsTuning_2.5
addpath('C:\Users\acb4ft\Desktop\WoundABM\woundABMSim\output\FinalCombinationWithMechanicsTuning_2.5_1');
modified_C=readModelData('UniaxC_2.5_20201014_094353');
modified_L=readModelData('UniaxL_2.5_20201014_094353');
modified_B=readModelData('Biax_2.5_20201014_094353');
modified_models={modified_C,modified_L,modified_B};

% % NoFibrin_NoInitialColllagen_ScaleStructuralCue_NoRotation_MechanicalSweep
% modified_C2=readModelData('UniaxC_10.0_20201007_130652_6');
% modified_L2=readModelData('UniaxL_10.0_20201007_130652_6');
% modified_B2=readModelData('Biax_10.0_20201007_130652_6');
% modified_models2={modified_C2,modified_L2,modified_B2};
% modified_C3=readModelData('UniaxC_10.0_20201007_131157_7');
% modified_L3=readModelData('UniaxL_10.0_20201007_131202_7');
% modified_B3=readModelData('Biax_10.0_20201007_131255_7');
% modified_models3={modified_C3,modified_L3,modified_B3};
% modified_C4=readModelData('UniaxC_10.0_20201007_131656_8');
% modified_L4=readModelData('UniaxL_10.0_20201007_131659_8');
% modified_B4=readModelData('Biax_10.0_20201007_131902_8');
% modified_models4={modified_C4,modified_L4,modified_B4};

% NoFibrin_NoInitialColllagen_ScaleStructuralCue_MechanicalSweep
% modified_C2=readModelData('UniaxC_10.0_20201007_124212');
% modified_L2=readModelData('UniaxL_10.0_20201007_124212_2');
% modified_B2=readModelData('Biax_10.0_20201007_124212_2');
% modified_models2={modified_C2,modified_L2,modified_B2};
% modified_C3=readModelData('UniaxC_10.0_20201007_124802_3');
% modified_L3=readModelData('UniaxL_10.0_20201007_124822_3');
% modified_B3=readModelData('Biax_10.0_20201007_124846_3');
% modified_models3={modified_C3,modified_L3,modified_B3};
% modified_C4=readModelData('UniaxC_10.0_20201007_125319_4');
% modified_L4=readModelData('UniaxL_10.0_20201007_125343_4');
% modified_B4=readModelData('Biax_10.0_20201007_125434_4');
% modified_models4={modified_C4,modified_L4,modified_B4};

% % NoFibrin_NoInitialColllagen_MechanicalSweep
% modified_C2=readModelData('UniaxC_10.0_20201007_121705_2');
% modified_L2=readModelData('UniaxL_10.0_20201007_121705_2');
% modified_B2=readModelData('Biax_10.0_20201007_121705_2');
% modified_models2={modified_C2,modified_L2,modified_B2};
% modified_C3=readModelData('UniaxC_10.0_20201007_122419_3');
% modified_L3=readModelData('UniaxL_10.0_20201007_122350_3');
% modified_B3=readModelData('Biax_10.0_20201007_122430_3');
% modified_models3={modified_C3,modified_L3,modified_B3};
% modified_C4=readModelData('UniaxC_10.0_20201007_123126_4');
% modified_L4=readModelData('UniaxL_10.0_20201007_123031_4');
% modified_B4=readModelData('Biax_10.0_20201007_123153_4');
% modified_models4={modified_C4,modified_L4,modified_B4};

figure(1); hold on;
styles={'r:','g:','b:'};
styles2={'r:','g:','b:'};
styles3={'r-.','g-.','b-.'};
styles4={'r--','g--','b--'};
mechanics={'UniaxC','UniaxL','Biax'};

for i=1:3
    % Plotting
    subplot(1,3,i); hold on;
    t=modified_models{i}.statistics.Time;
    plot(t/24,modified_models{i}.statistics.ColMVL,styles{i},'LineWidth',2);

%     t=modified_models2{i}.statistics.Time;
%     plot(t/24,modified_models2{i}.statistics.ColMVL,styles2{i},'LineWidth',2);
%     plot(t/24,modified_models3{i}.statistics.ColMVL,styles3{i},'LineWidth',2);
%     plot(t/24,modified_models4{i}.statistics.ColMVL,styles4{i},'LineWidth',2);
    if strcmp(mechanics{i},'UniaxC')
        plot(t/24,original_models{i}.statistics.ColMVL,'r.-','MarkerFaceColor','k','LineWidth',2);
        errorbar(21.538,0.433,(0.592-0.433),'o','Color','k','MarkerFaceColor','r','LineWidth',1.5);
    elseif strcmp(mechanics{i},'Biax')
        plot(t/24,original_models{i}.statistics.ColMVL,'b.-','MarkerFaceColor','k','LineWidth',2);
        errorbar(20.551,0.103,(0.28-0.103),'o','Color','k','MarkerFaceColor','b','LineWidth',1.5);
    elseif strcmp(mechanics{i},'UniaxL')
        plot(t/24,original_models{i}.statistics.ColMVL,'g.-','MarkerFaceColor','k','LineWidth',2);
        errorbar(7,0.52,(0.75-0.52),'o','Color','k','MarkerFaceColor','g','LineWidth',1.5);
        errorbar(14,0.39,(0.52-0.39),'o','Color','k','MarkerFaceColor','g','LineWidth',1.5);
        errorbar(21,0.38,(0.49-0.38),'o','Color','k','MarkerFaceColor','g','LineWidth',1.5);
        errorbar(42,0.42,(0.66-0.42),'o','Color','k','MarkerFaceColor','g','LineWidth',1.5);
    end
    
    % Formatting
    ylim([0 0.8]); yticks([0 0.2 0.4 0.6 0.8]);
    xticks([0 7 14 21 28 35 42]);
    xlim([0 42]);
    set(gca,'XTickLabel',{'0','7','14','21','28','35','42'},'FontName', 'Arial', 'FontSize', 14);
    set(gca, 'PlotBoxAspectRatio', [1.5 1 1], 'LineWidth', 1, 'FontName', 'Arial', 'FontSize', 14);
    if i==1
%         title('Circumferential Loading','FontName', 'Arial', 'FontSize', 14);
        ylabel('Collagen MVL', 'FontName', 'Arial', 'FontSize', 14);
    elseif i==2
%         title('Longitudinal Loading','FontName', 'Arial', 'FontSize', 14);
        xlabel('Time (d)', 'FontName', 'Arial', 'FontSize', 14);
    elseif i==3
%         title('Biaxial Loading','FontName', 'Arial', 'FontSize', 14);
        L(1) = plot(nan,nan,'-','Color',[.5,.5,.5],'LineWidth',2);
        L(2) = plot(nan(10,1),nan(10,1),':','Color',[.5,.5,.5],'LineWidth',2);
        L(3) = plot(nan,nan,'-o','Color','k','MarkerFaceColor',[.5,.5,.5],'LineWidth',1.5);
        legend(L,{'Standard','Modified','Experimental'},'Location','NorthEast','FontName','Arial','FontSize',14);
%         L(3) = plot(nan(10,1),nan(10,1),'-.','Color',[.5,.5,.5],'LineWidth',2);
%         L(4) = plot(nan(10,1),nan(10,1),'--','Color',[.5,.5,.5],'LineWidth',2);
%         L(5) = plot(nan,nan,'-o','Color','k','MarkerFaceColor',[.5,.5,.5],'LineWidth',1.5);
%         legend(L,{'Standard','Modified, W_m=0.2','Modified, W_m=0.3','Modified, W_m=0.4','Experimental'},'Location','NorthEast','FontName','Arial','FontSize',14);
    end
end