% This script plots the figures validating the Repast WoundABM against the 
% original MATLAB ABM (published J Physiol 2012) and experimental data 
% generated by Greg Fomovsky and Laura Caggiano.

% Author: Arlynn C Baker
% Created: 2019/06/30

clear; clc; close all;
%% All meachincs and grid sizes
addpath('C:\Users\acb4ft\Desktop\WoundABM\woundABMSim\output\Standard');
% original_C=readModelData('UniaxC_2.5_20200922_130643');
% original_L=readModelData('UniaxL_2.5_20200922_130706');
% original_B=readModelData('Biax_2.5_20200922_130618');
% original_C=readModelData('UniaxC_10.0_20200917_161545');
% original_L=readModelData('UniaxL_10.0_20200917_163634');
% original_B=readModelData('Biax_10.0_20200917_160011');

addpath('C:\Users\acb4ft\Desktop\WoundABM\woundABMSim\output\test');
% modified_C=readModelData('');
% modified_L=readModelData('');
% modified_B=readModelData('Biax_10.0_20201028_213855');
% modified_B=readModelData('Biax_10.0_20201028_213856');
modified_B=readModelData('Biax_10.0_20201028_2138552');

% plotRepastABMStats(1,{'r--','r-'},modified_C, original_C);
% plotExperimentalData(1,'UniaxC');
% formatStatPlot(1,{'Modified','Standard','Experimental'});

% plotRepastABMStats(1,{'g--'},modified_L);
% plotExperimentalData(1,'UniaxL');
% formatStatPlot(1,{'Modified','Standard','Experimental'});

plotRepastABMStats(1,{'b-'},modified_B);
plotExperimentalData(1,'Biax');
formatStatPlot(1,{'Modified','Standard','Experimental'});


% C25_IDs={'UniaxC_2.5_20200922_130643'};
% C5_IDs={'UniaxC_5.0_20200922_130754'};
% C10_IDs={'UniaxC_10.0_20200917_161545'};
% 
% L25_IDs={'UniaxL_2.5_20200922_130706'};
% L5_IDs={'UniaxL_5.0_20200922_130820'};
% L10_IDs={'UniaxL_10.0_20200917_163634'};
% 
% B25_IDs={'Biax_2.5_20200922_130618'};
% B5_IDs={'Biax_5.0_20200922_130728'};
% B10_IDs={'Biax_10.0_20200917_160011'};
% 
% model_C25=readModelData(C25_IDs{1});
% model_C5=readModelData(C5_IDs{1});
% model_C10=readModelData(C10_IDs{1});
% plotRepastABMStats(1,{'r:','r-.','r--'},model_C25, model_C5, model_C10);
% plotMatlabABMStats(1,'UniaxC');
% plotExperimentalData(1,'UniaxC');
% formatStatPlot(1,{'Repast 2.5 \mum grid','Repast 5 \mum grid','Repast 10 \mum grid','MATLAB Continuous','Experimental'});
% 
% model_L25=readModelData(L25_IDs{1});
% model_L5=readModelData(L5_IDs{1});
% model_L10=readModelData(L10_IDs{1});
% plotRepastABMStats(2,{'g:','g-.','g--'},model_L25, model_L5, model_L10);
% plotMatlabABMStats(2,'UniaxL');
% plotExperimentalData(2,'UniaxL');
% formatStatPlot(2,{'Repast 2.5 \mum grid','Repast 5 \mum grid','Repast 10 \mum grid','MATLAB Continuous','Experimental'});
% 
% model_B25=readModelData(B25_IDs{1});
% model_B5=readModelData(B5_IDs{1});
% model_B10=readModelData(B10_IDs{1});
% plotRepastABMStats(3,{'b:','b-.','b--'},model_B25, model_B5, model_B10);
% plotMatlabABMStats(3,'Biax');
% plotExperimentalData(3,'Biax');
% formatStatPlot(3,{'Repast 2.5 \mum grid','Repast 5 \mum grid','Repast 10 \mum grid','MATLAB Continuous','Experimental'});