% This script plots the figures validating the Repast WoundABM against the 
% original MATLAB ABM (published J Physiol 2012) and experimental data 
% generated by Greg Fomovsky.

% Author: Arlynn C Baker
% Created: 2019/06/30

% C25_IDs={''};
% C5_IDs={''};
% C10_IDs={''};
% 
% L25_IDs={''};
% L5_IDs={''};
% L10_IDs={''};
% 
% B25_IDs={''};
% B5_IDs={''};
% B10_IDs={''};

clear; clc
%% Standard
% addpath('C:\Users\acb4ft\Desktop\WoundABM\woundABMSim\output');
% ID = {'UniaxC_2.5_20200117_143101'};% Substitute persistence
% ID = {'UniaxC_2.5_20200116_213724'}; % Substitute mechanics
% ID = {'UniaxC_2.5_20200116_205826'}; % Substitute structure
% ID = {'UniaxC_2.5_20200116_152954'}; % Substitute all
% ID = {'UniaxC_2.5_20200116_135135'}; % Chemo substitute
% ID = {''};
% ID = {'Biax_2.5_20191230_174325'};
% ID = {'UniaxC_2.5_20200103_170602'};
% ID = {'UniaxL_2.5_20200103_174201'};

% model=readModelData(ID{1});
% plotRepastABMStats(3,model);
% formatStatPlot(3,{'MatLab','Repast 2.5 \mu m'});

%% Standard
addpath('C:\Users\acb4ft\Desktop\WoundABM\woundABMSim\output\CellSpeedZero');
C25_IDs={'UniaxC_2.5_20200117_175420'};
% C5_IDs={''};
% C10_IDs={''};

L25_IDs={'UniaxL_2.5_20200117_175420'};
% L5_IDs={''};
% L10_IDs={''};

B25_IDs={'Biax_2.5_20200117_175420'};
% B5_IDs={''};
% B10_IDs={''};

model_C25=readModelData(C25_IDs{1});
% model_C5=readModelData(C5_IDs{1});
% model_C10=readModelData(C10_IDs{1});
plotRepastABMStats(1,model_C25);%, model_C5, model_C10);
% plotMatlabABMStats(1,'UniaxC');
formatStatPlot(1,{'Repast 2.5 \mu m','MATLAB Continuous','Experimental'});%'Repast 5 \mu m','Repast 10 \mu m',

model_L25=readModelData(L25_IDs{1});
% model_L5=readModelData(L5_IDs{1});
% model_L10=readModelData(L10_IDs{1});
plotRepastABMStats(2,model_L25)%, model_L5, model_L10);
% plotMatlabABMStats(2,'UniaxL');
formatStatPlot(2,{'Repast 2.5 \mu m','MATLAB Continuous','Experimental'});

model_B25=readModelData(B25_IDs{1});
% model_B5=readModelData(B5_IDs{1});
% model_B10=readModelData(B10_IDs{1});
plotRepastABMStats(3,model_B25);%, model_B5, model_B10);
% plotMatlabABMStats(3,'Biax');
formatStatPlot(3,{'Repast 2.5 \mu m','MATLAB Continuous','Experimental'});